language: node_js
node_js:
  - node
  - 8
  - 6
  - 4

cache: yarn

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

before_install:
  - which npx || yarn global add npx

script:
  - npx nyc yarn test

after_success:
  - '[ $TRAVIS_NODE_VERSION = node ] && npx nyc report --reporter=lcov && npx codecov'

notifications:
  email: false
  
deploy:
  provider: npm
  skip_cleanup: true
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: vitarn/qcloud-apigateway
    node: node
