language: node_js
node_js:
  - node
  - 8
  - 6
  - 4

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

cache: yarn

before_install:
  - which npx || yarn global add npx

script:
  - yarn build && npx nyc yarn test

after_success:
  - npx nyc report --reporter=lcov && npx codecov
  
jobs:
  include:
    - stage: deploy
      script: skip
      after_success: echo Ready deploy...
      deploy:
        provider: npm
        skip_cleanup: true
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        on:
          tags: true
          repo: vitarn/qcloud-apigateway
          node: node

notifications:
  email: false
